#!/bin/bash
SUCCESS=0
E_DB=99    # Error code for missing entry.

declare -A address
#       -A option declares associative array.



if [ -f SMART.log ]
then
    rm SMART.log
fi

if [ -f HDDs.log ]
then
    rm HDDs.log
fi

smartctl --scan | awk '{print $1}' >> HDDs.log
lspci | grep -i raid >> HDDs.log

getArray ()
{
    i=0
    while read line # Read a line
    do
        array[i]=$line # Put it into the array
        i=$(($i + 1))
    done < $1
}

getArray "HDDs.log"


for e in "${array[@]}"
do
    if [[ $e =~ /dev/sd* || $e =~ /dev/hd* ]]
        then
            echo "smartctl -i -A $e" >> SMART.log
            smartctl -i -A $e >> SMART.log # Run smartctl into all disks that the host have
    fi
done
exit $?   # In this case, exit code = 99, since that is function return.
